from groq import Groq
from dotenv import load_dotenv
import os

# Load environment variables from .env
load_dotenv()

# Initialize Groq client
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def generate_llama_response(prompt: str) -> str:
    """
    Generate a response from LLaMA 3.1 hosted on Groq.
    
    Args:
        prompt (str): The user's prompt.

    Returns:
        str: The response generated by the model.
    """
    try:
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",  # Updated to correct Groq model name
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0.8,
            max_tokens=1024,
            top_p=1,
            stream=False
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"[Groq Error] {str(e)}"

# Replace Gemini calls with LLaMA responses
def get_crypto_news():
    return generate_llama_response("Give me the latest 3 crypto news headlines with short summaries (not older than 2 days).Output format rules: Headings should be in uppercase without any formatting.Points should be numbered using only numbers (1., 2., 3.).No bold, italics, or markdown formatting.Do not include decorative symbols or extra punctuation.")

def wallet_summary(address: str, balance_eth: float):
    return generate_llama_response(f"Explain the wallet address {address}'s activity. Current ETH balance: {balance_eth}. Return a summary like a report.Output format rules: Headings should be in uppercase without any formatting.Points should be numbered using only numbers (1., 2., 3.).No bold, italics, or markdown formatting.Do not include decorative symbols or extra punctuation.")

def check_scam_token(token_address: str):
    return generate_llama_response(f"Is the token with address {token_address} suspicious or safe? Provide a brief reasoningOutput format rules: Headings should be in uppercase without any formatting.Points should be numbered using only numbers (1., 2., 3.).No bold, italics, or markdown formatting.Do not include decorative symbols or extra punctuation.")